#!/bin/sh

if [[ $# -ne 0 ]] ; then
	set -- "-font" $1
fi

# Use Graphicksmagic if we have it
if command -v gm >/dev/null; then
	GM="gm"
else
	GM=""
fi

# Set filepaths
IMAGE="/tmp/screenshot.png"
GRADIENT="/tmp/you_died_gradient.jpg"

# Get grayscale screenshot
$GM import -window root \
           -colorspace GRAY \
           $IMAGE

# Get screen resolution
SIZE=$(xrandr  | grep \* | cut -d' ' -f4)

# Create Gradient
echo "P2 1 11 8  8 8 8 8 1 1 1 8 8 8 8 " | \
	$GM convert - -filter cubic -resize $SIZE\! $GRADIENT

# Apply overlay
$GM composite $IMAGE -compose Multiply $GRADIENT \
              $IMAGE

# Add words
$GM convert $IMAGE \
            -gravity Center \
            "$@" \
            -fill "#5d0d0d" \
            -pointsize 120 \
            -draw "text 0,0 'YOU DIED'" \
            $IMAGE

i3lock -i $IMAGE
# feh $IMAGE
