#!/bin/sh

if [[ $# -ne 0 ]] ; then
	set -- "-font" $1
fi

# Create config folder
config_dir=$HOME/.config/dshlock
mkdir -p $config_dir

# Get screen resolution
size=$(xrandr  | grep \* | cut -d' ' -f4)
grad_filename=$config_dir/gradient-${size}.gif

# Get screenshot
import -window root /tmp/screenshot.png

# Create Gradient if it doesn't exist
if [[ ! -f $grad_filename ]] ; then
	convert -size $size gradient: \
	        -function sinusoid 1,90 \
	        $grad_filename
fi

# Apply overlay
composite /tmp/screenshot.png -compose Multiply $grad_filename \
          /tmp/screenshot.png

# Add words & grayscale
convert /tmp/screenshot.png \
        -type Grayscale \
        -gravity Center \
        "$@" \
        -stroke "#5d0d0d" -fill "#5d0d0d" \
        -pointsize 120 \
        -annotate 0 "YOU DIED" \
        /tmp/screenshot.png

# i3lock -i /tmp/screenshot.png
feh /tmp/screenshot.png
