#!/bin/sh

if [[ $# -ne 0 ]] ; then
	set -- "-font" $1
fi

# Use Graphicksmagic if we have it
if command -v gm >/dev/null; then
	IMPORT="gm import"
	CONVERT="gm convert"
	COMPOSITE="gm composite"
else
	IMPORT="import"
	CONVERT="convert"
	COMPOSITE="composite"
fi

# Create cache folder
cache_dir=$HOME/.cache/dshlock
mkdir -p $cache_dir

# Get screen resolution
size=$(xrandr  | grep \* | cut -d' ' -f4)
grad_filename=$cache_dir/gradient-${size}.png

# Get grayscale screenshot
$IMPORT -window root \
        -colorspace GRAY \
        /tmp/screenshot.png

# Create Gradient if it doesn't exist
if [[ ! -f $grad_filename ]] ; then
	convert -size $size gradient: \
	        -function sinusoid 1,90 \
	        $grad_filename
fi

# Apply overlay
$COMPOSITE /tmp/screenshot.png -compose Multiply $grad_filename \
           /tmp/screenshot.png

# Add words
$CONVERT /tmp/screenshot.png \
         -gravity Center \
         "$@" \
         -fill "#5d0d0d" \
         -pointsize 120 \
         -draw "text 0,0 'YOU DIED'" \
         /tmp/screenshot.png

i3lock -i /tmp/screenshot.png
# feh /tmp/screenshot.png
